# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be84cd092f3ebe61149267de44a3adb2ac5e66cbefa95c2e4ac2c485c60c8d2e5ef610d5d790e1c2043e7b19b48d8d43e6337ed15dbefc2610cf74a186d6b8bb

test:
  secret_key_base: 522ebc34ac3476c10080280ce894b97cec29df6cc9480b7d9c9c7fb69309a1c0415c8ff9ba1d1068fb020f336222fcb1c89ffa59d4929375499d3be78091fe43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
